concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
jobs:
  Linux-mkspecs:
    uses: steinwurf/linux-mkspecs-action/.github/workflows/action.yml@6.0.0
    with:
      extra_resolve_options: ${{ github.events.inputs.extra_resolve_options }}
      test_command: python3 waf --run_tests --run_cmd="%s --no_fail"
name: Linux C++ make-specs
'on':
  pull_request: null
  push:
    branches:
    - master
  schedule:
  - cron: 0 1 * * *
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: Extra Resolve Options
        required: false
