name: Valgrind
'on':
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: Extra Resolve Options
        required: false
  push:
    branches:
    - master
  pull_request:
jobs:
  valgrind:
    name: Valgrind
    uses: steinwurf/valgrind-action/.github/workflows/action.yml@5.0.0
    with:
      extra_resolve_options: ${{ github.events.inputs.extra_resolve_options }}
      test_command: python3 waf --run_tests --run_cmd="valgrind %s --no_fail"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
