concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
jobs:
  valgrind:
    name: Valgrind
    uses: steinwurf/valgrind-action/.github/workflows/action.yml@5.0.0
    with:
      extra_resolve_options: ${{ github.events.inputs.extra_resolve_options }}
      test_command: python3 waf --run_tests --run_cmd="valgrind %s --no_fail"
name: Valgrind
'on':
  pull_request: null
  push:
    branches:
    - master
  schedule:
  - cron: 0 1 * * *
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: Extra Resolve Options
        required: false
